# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A43NNE2Li7gJEpNZRvbX2fYFEs30kSbw
"""

import numpy as np

PI_ZERO = np.array([[0.5, 0.5]])

P1 = np.array([[1 / 2, 1 / 2], [2 / 5, 3 / 5]])
R1 = np.array([[9, 3], [3, -7]])

P2 = np.array([[0.8, 0.2], [0.7, 0.3]])
R2 = np.array([[4, 4], [1, -19]])

Q1 = np.array([[sum((P1[0] * R1[0]))], [sum(P1[1] * R1[1])]])
Q2 = np.array([[sum((P2[0] * R2[0]))], [sum(P2[1] * R2[1])]])

# Question 1
print("***** Question 1 *****")

pii = PI_ZERO
for i in range(100):
    pii = np.dot(pii, P1)
    print("n = " + str(i + 1))
    print("p1: " + str(pii[0][0]) + ", p2: " + str(pii[0][1]))

# Question 2
print("***** Question 2 *****")

v_zero = np.array([[0]] * P1.ndim)
v = v_zero
for i in range(100):
    v = Q1 + np.dot(P1, v)
    print("n = " + str(i + 1))
    print("v1: " + str(v[0][0]) + ", v2: " + str(v[1][0]))

# Question 3
print("***** Question 3 *****")


def get_max(l):
    max_val = max(l)
    max_idx = l.index(max_val)
    return max_idx + 1, max_val


d1 = np.array([[0]] * P1.ndim)
d2 = np.array([[0]] * P2.ndim)
v_zero = np.array([[0]] * P1.ndim)
v = v_zero
for i in range(100):
    vd1 = Q1 + np.dot(P1, v)
    vd2 = Q2 + np.dot(P2, v)
    l1 = [vd1[0][0], vd2[0][0]]
    l2 = [vd1[1][0], vd2[1][0]]
    mi1, mv1 = get_max(l1)
    mi2, mv2 = get_max(l2)
    v = np.array([[mv1], [mv2]])
    d = np.array([[mi1], [mi2]])
    print("n = " + str(i + 1))
    print("v1: " + str(v[0][0]) + ", v2: " + str(v[1][0]))
    print("d1: " + str(d[0][0]) + ", d2: " + str(d[1][0]))